# CI name , it will display on github's action page menu
name: BuildPythonChromeDockerFile
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [main]
# CI enviroment settings
env:
  STATE_RELEASE_VERSION: "1.0" # chrome version
jobs:
  build:
    name: 构建,发布
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # here are some step followed , each step must have `uses` or `run` key , for CI to run
      # other key like `name`,`with`,`env` is optional
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Get chrome version
        run: |
          python chromeversion.py
      - name: Get chrome driver version
        run: |
          python chromedriverversion.py
      
      - name: Get chrome driver version
        run: |
          python chromedriverversion.py
      - name: Output Docker info
        run: docker info
      - name: read chrome_version file
        run: echo chrome_version
      
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: includeno/pythonchrome
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"