# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: BuildPythonChromeDockerFile
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [main]
# CI enviroment settings
env:
  STATE_RELEASE_VERSION: "1.0" # chrome version
jobs:
  build:
    name: 构建,发布
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # here are some step followed , each step must have `uses` or `run` key , for CI to run
      # other key like `name`,`with`,`env` is optional
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Get chrome version
        run: |
          python chromeversion.py

      - name: Get chrome driver version
        run: |
          python chromedriverversion.py

      - name: Output Docker info
        run: docker info
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: tail from chrome_version to GITHUB_ENV
        run: tail ./chrome_version >> $GITHUB_ENV
      - name: set tag python version
        run: tail ./dockerpythonversion >> $GITHUB_ENV
          sed 'python:3.9.4c\${{env.PythonVersion}}' Dockerfile
      - name: check chrome_version
        run:  |
          echo ${{env.ChromeVersion}}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #版本号第一位不允许空格
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "includeno/pythonchrome:latest,includeno/pythonchrome:chrome${{ env.ChromeVersion }}"
          push: true
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"
    
   