# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: Build Example simple_selenium Docker Image
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [simple_selenium]
# CI enviroment settings
env:
  TAG_NAME: "simple_selenium"
  VERSION: "0.1"
jobs:
  build:
    name: 构建,发布
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      # here are some step followed , each step must have `uses` or `run` key , for CI to run
      # other key like `name`,`with`,`env` is optional
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Output Docker info
        run: docker info
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #版本号第一位不允许空格 https://github.com/docker/build-push-action
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./example/simple_selenium
          #构造环境变量传入list https://github.com/docker/build-push-action
          # tag 不允许出现-
          tags: "includeno/${{ env.TAG_NAME }}:latest,includeno/${{ env.TAG_NAME }}:${{ env.VERSION }}"
          push: true
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"